DROP TRIGGER Update_Labels_Timestamp on Labels;
DROP TABLE Labels;
DROP TABLE Error_Events;
DROP TABLE Errors;
DROP TRIGGER Update_Error_Sources_Timestamp on Error_Sources;
DROP TABLE Error_Sources;
DROP TABLE Person_Permissions;
DROP TABLE Role_Permissions;
DROP TABLE Permissions;
DROP TABLE Person_Urls;
DROP TABLE Role_Urls;
DROP TABLE Restricted_Urls;
DROP TABLE Impersonate_Permissions;
DROP TRIGGER Update_Role_Assignments_Timestamp on Role_Assignments;
DROP TABLE Role_Assignments;
DROP TRIGGER Update_Roles_Timestamp on Roles;
DROP TABLE Roles;
DROP TRIGGER Update_Users_Timestamp on Users;
DROP TABLE Users;
DROP TRIGGER Update_Sites_Timestamp on Sites;
DROP TABLE Sites;
DROP TABLE Languages;
DROP TYPE Error_Severity;
DROP TYPE User_Status;
DROP FUNCTION Update_Last_Updated_Column();
