var FileAPI = {
    "version": {},
    "cors": {},
    "html5": {},
    "media": {},
    "formData": {},
    "debug": {},
    "pingUrl": {},
    "multiFlash": {},
    "flashAbortTimeout": {},
    "withCredentials": {},
    "staticPath": {},
    "flashUrl": {},
    "flashImageUrl": {},
    "postNameConcat": function () {},
    "ext2mime": {
        "jpg": {},
        "tif": {},
        "txt": {}
    },
    "accept": {
        "image/*": {},
        "audio/*": {},
        "video/*": {}
    },
    "chunkSize": {},
    "chunkUploadRetry": {},
    "chunkNetworkDownRetryTimeout": {},
    "KB": {
        "from": function () {}
    },
    "MB": {
        "from": function () {}
    },
    "GB": {
        "from": function () {}
    },
    "TB": {
        "from": function () {}
    },
    "expando": {},
    "uid": function () {},
    "log": function () {},
    "newImage": function () {},
    "getXHR": function () {},
    "isArray": function () {},
    "support": {
        "dnd": {},
        "cors": {},
        "html5": {},
        "chunked": {},
        "dataURI": {},
        "accept": {},
        "multiple": {},
        "transform": {},
        "canvas": {},
        "media": {},
        "flash": {}
    },
    "event": {
        "on": function () {},
        "off": function () {},
        "one": function () {},
        "fix": function () {},
        "dnd": function () {}
    },
    "throttle": function () {},
    "F": function () {},
    "parseJSON": function () {},
    "trim": function () {},
    "defer": function () {},
    "queue": function () {},
    "each": function () {},
    "afor": function () {},
    "extend": function () {},
    "isFile": function () {},
    "isCanvas": function () {},
    "getFilesFilter": function () {},
    "readAsDataURL": function () {},
    "readAsBinaryString": function () {},
    "readAsArrayBuffer": function () {},
    "readAsText": function () {},
    "toDataURL": function () {},
    "toBinaryString": function () {},
    "readAsImage": function () {},
    "checkFileObj": function () {},
    "getDropFiles": function () {},
    "getFiles": function () {},
    "getTotalSize": function () {},
    "getInfo": function () {},
    "addInfoReader": function () {},
    "filter": function () {},
    "filterFiles": function () {},
    "upload": function () {},
    "_getFilesDataArray": function () {},
    "_getFormData": function () {},
    "reset": function () {},
    "load": function () {},
    "encode64": function () {},
    "flashWebcamUrl": {},
    "renderImageToCanvas": function () {},
    "Image": function () {},
    "Form": function () {},
    "XHR": function () {},
    "Camera": function () {}
}
